/**
  Generated main.h file from MPLAB Code Configurator

  @Company
    Microchip Technology Inc.

  @File Name
    main.h

  @Summary
    This is the generated main.c using PIC24 / dsPIC33 / PIC32MM MCUs.

  @Description
    This source file provides main entry point for system initialization and application code development.
    Generation Information :
        Product Revision  :  PIC24 / dsPIC33 / PIC32MM MCUs - 1.169.0
        Device            :  PIC24FJ128GA705
    The generated drivers are tested against the following:
        Compiler          :  XC16 v1.50
        MPLAB 	          :  MPLAB X v5.40
*/

/*
    (c) 2020 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
*/

#define COMMAND_NUMBYTES 1
#define INDEX_NUMBYTES 1
#define LENGTH_NUMBYTES 2
#define HEADER_NUMBYTES (COMMAND_NUMBYTES + INDEX_NUMBYTES + LENGTH_NUMBYTES)
#define PAYLOAD_NUMBYTES 1024
#define TXBUFFSIZE_NUMBYTES (COMMAND_NUMBYTES + INDEX_NUMBYTES + LENGTH_NUMBYTES + PAYLOAD_NUMBYTES)
#define RXBUFFSIZE_NUMBYTES TXBUFFSIZE_NUMBYTES
#define DATAFRAMES_TOTAL2SEND_SW0 1
#define DATAFRAMES_TOTAL2SEND_SW1 8
#define CMD_CHAR_SW0 'T'
#define CMD_CHAR_SW1 't'
#define INDEX_VAL_INT_1  1
#define INDEX_VAL_INT_2  2
#define INDEX_VAL_INT_3  3
#define INDEX_VAL_INT_4  4
#define INDEX_VAL_DBL_1  5
#define INDEX_VAL_DBL_2  6
#define INDEX_VAL_FLT_1  7
#define INDEX_VAL_FLT_2  8
#define INDEX_VAL_LNG    9
#define INDEX_VAL_BOOL  10
#define INDEX_VAL_STR_1 11
#define INDEX_VAL_STR_2 12
#define INDEX_VAL_STR_3 13
#define INDEX_VAL_STR_4 14
#define CMD_INDEX_MIN_SW0 INDEX_VAL_INT_1
#define CMD_INDEX_MIN_SW1 INDEX_VAL_STR_1
#define CMD_INDEX_MAX INDEX_VAL_STR_4

/**
 End of File
*/
